# Generated by Django 4.2.7 on 2023-11-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='formularios',
            field=models.IntegerField(default=1),
        ),
    ]
